FROM docker:cli

# -----
# install python
# -----

ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# -----
# finish install python
# -----

WORKDIR /app
COPY ./backend/requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY ./backend/ .