version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: "gunicorn -k gevent -w 1 app:app -b :5000"
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend