version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: "gunicorn --worker-class eventlet -w 1 app:app -b :5000"
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#   frontend:
#     container_name: frontend
#     restart: always
#     build: ./frontend
#     environment:
#       - BASE_URL=http://nginx
#     command: "yarn start --hostname 0.0.0.0 --port 8000"
#     expose:
#       - "3000"
#   nginx:
#     container_name: nginx
#     restart: always
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - static-volume:/static
#       - ./nginx:/etc/nginx/conf.d
#     depends_on:
#       - backend
# volumes:
#   static-volume: